# Generated by Django 4.2.10 on 2024-02-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default=False, max_length=255),
        ),
    ]
